from .admin import admin_bp
from .auth import auth_bp
from .cart import cart_bp
from .main import main_bp
from .payment import payment_bp
from .products import products_bp
from .users import users_bp
from .api import api_bp
from .devices import devices_bp